name: 'Terraform Apply'
on:
    push:
      branches:
        - main
  
env:
  TF_CLOUD_ORGANIZATION: "shaqs-org"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "terraform-github"
  CONFIG_DIRECTORY: "./terraform"
  
jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: 'Configure AWS credentials'
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-south-1
            audience: sts.amazonaws.com
        - name: Upload Configuration
          uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
          id: apply-upload
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            directory: ${{ env.CONFIG_DIRECTORY }}
        - name: Install Dependencies
          run: |
            npm i
      
        - name: Build Static Website
          run: npm run build
      
        - name: Copy files to the production website with the AWS CLI
          run: |
            aws s3 sync --delete ./ s3://portfolio-bucket-shaqran
      
        - name: Copy files to the production website with the AWS CLI
          run: |
            aws cloudfront create-invalidation \
              --distribution-id ${{ secrets.DIST_ID }} \
              --paths "/*"